[pytest]
; 自动发现测试文件的路径
testpaths = 
    test_cases
    ; test_cases/test_goods_transfer_In.py
; 定义命令行默认参数
addopts = 
    -vs                   
    --capture=no         
    --alluredir=./temp   
; 配置日志
python_files = test*
python_classes = Test*
python_functions = test*
markers =
    smoke: 冒烟测试
    run: 执行顺序
log_cli = true
log_cli_level = INFO